### ISSUE TITLE
Support exact match for tags

### ISSUE THREAD

**Issue by LaurenceBarnes** [varthe/Redirecterr#14]
Hi, it seems you allow issues raised again - and I do have a small issue to report.

In my setup, series and movies with the tag `anime` get redirected to their respective anime-specific instance. This works flawlessly.

However, I did have one incident where a series with the tag `based on anime` was sent to the anime instance as well. E.g. https://www.themoviedb.org/tv/85462?language=en is a live action series and would then be wrongly redirected to the anime instance.

It would be nice if there was a setting that could let the user decide if a specific tag (like an additional line you could add under each tag) that we want as a filter, needs to be an exact match, or work the current way.

with kind regards!

**Comment by varthe** [comment]
I created a beta image for this. Do you mind giving it a test?
Change image to `varthe/redirecterr:beta`
In your `config.yaml` use the new `require:` option, e.g:
```yaml  
  - media_type: tv
      conditions:
          keywords:
              require:
                  - anime
```
This will match when the exact keyword "anime"

**Comment by LaurenceBarnes** [comment]
hi, thanks for the quick change - works flawlessly!

Please add this to the example config though for others - took some trial and error to figure out the 4k feature that we had a while ago :D

you can just "steal" from my config, hope that helps with putting it in the example config somehow :D

```
filters:
  - media_type: movie
    is_not_4k: True # match if not 4k
    is_4k: False # also required to match if not 4k
    conditions:
      keywords: anime # Match if keyword "anime" is present
    apply: radarr_anime # Send request to "radarr_anime"
  - media_type: movie
    is_not_4k: False # also required to match if 4k
    is_4k: True # match if 4k
    conditions:
      keywords: anime # Match if keyword "anime" is present
    apply: radarr_anime_uhd # Send request to "radarr_anime_uhd"
  - media_type: tv
    conditions:
      keywords:
        require: anime # Exact match if keyword "anime" is present (excludes tags like "based on anime")
    apply: sonarr_anime # Send request to "sonarr_anime"
```

**Comment by varthe** [comment]
You shouldn't need both `is_not_4k` and `is_4k`. One should be enough. What happens when you only have one?

**Comment by LaurenceBarnes** [comment]
the config validation throws errors. I did try it back then when you added that feature

edit: and I think I even went through the code to figure it out, and there was something that suggested that it is necessary

**Comment by varthe** [comment]
I'm not getting any errors using this config:
```yaml
filters:
    - media_type: movie
      is_not_4k: true
      apply: radarr
```
Can you try again? I might have fixed it and forgot to let you know
