### ISSUE TITLE
Filter based on amount of seasons/episodes

### ISSUE THREAD

**Issue by OnniSaarni** [varthe/Redirecterr#16]
I don't think it is currently possible to do something like this but would be pretty cool to see something like this.

I'd like to deny or maybe just leave the request to be manually approved if for example a user requests more than 3 seasons at a time (configurable number).

Also would be nice to have the option of excluding these filters from specific users. As far as I know these things aren't possible at the moment but please do let me know if I'm wrong.

Been using the app for a couple of months now and it's awesome. Thank you so much for making it! <3

**Comment by varthe** [comment]
You can already include usernames and emails in filters. And you can disable automatic approval for an instance.

But you can't filter by the number of requested seasons, so I'll implement it sometime this week. I'll let you know when it's out

**Comment by OnniSaarni** [comment]
Thank you so much! I could even contribute myself but I don't really play well with js. Thanks for the tips as well!

**Comment by varthe** [comment]
I just pushed the changes to the beta image: `varthe/redirecterr:beta`. Can you give it a test? The rewrite is also included in the beta image but it should work with your existing config

The new condition is called `max_seasons`. If it exceeds the number of seasons requested (including specials) it will reject the filter.

Add it to your filters like this:
```yaml
    - media_type: tv
      conditions:
        max_seasons: 1
      apply: sonarr
```

To stop it auto approving you can either:
Create a new instance with `approve: false` like this:
```yaml
instances:
  sonarr_no_approve: 
    server_id: 0
    root_folder: "/mnt/plex/Shows"
    approve: false
  sonarr: 
    server_id: 0
    root_folder: "/mnt/plex/Shows"
```

Or set `approve_on_no_match` to `false`. This will stop auto approving ANY unmatched requests.
