### ISSUE TITLE
Bug: "duplicated mapping key" when using exact match filters

### ISSUE THREAD

**Issue by LaurenceBarnes** [varthe/Redirecterr#20]
Hi, thanks again for implementing the exact match filter.

I did encounter an issue that likely could be considered a bug.

So I wanted to add the tag "anime inspired" to the exact match filter, because this tag is also used for series that could be considered anime (unlike other tags such as "based on anime", that made me raise the previous feature request).

I did it as follows:

```
    conditions:
      keywords:
        require: anime # Exact match if keyword "anime" is present
        require: anime inspired
```

however, this caused `redirecterr  | 2025-06-09 16:22:59 [ERROR]: Error loading config: duplicated mapping key (43:9)`.

This error makes sense with normal keyword filters, but not with exact match filters. It would be awesome if the exact match keywords would not conflict with each other, unless they are an actualy duplicate :D 

with kind regards

**Comment by LaurenceBarnes** [comment]
for other idiots like me, the configuration must be like

```
  - media_type: tv
    conditions:
      keywords:
        require: ["anime", "anime inspired", "donghua"] # Exact match if keywords are present
    apply: sonarr_anime # Send request to "sonarr_anime"
```

In order to work.
