### ISSUE TITLE
Redirecterr not redirecting according to filter

### ISSUE THREAD

**Issue by privateoutlaw** [varthe/Redirecterr#3]
Hello,

I have installed Redirecterr on Unraid using it's Community template and set all the files accordingly, although it doesn't seem to actually do anything based on the filter.

My config is as follows;

```
overseerr_url: ""#####################################"" 
overseerr_api_token: "#####################################"

instances:
  Radarr: # Custom instance name
    server_id: 0
    root_folder: "/media/Movies"
    approve: true
  Sonarr: # Custom instance name
    server_id: 0
    root_folder: "/media/tv"
    approve: true
  Anime: # Custom instance name
    server_id: 1
    root_folder: "/media/anime"
    approve: true

filters:
  - media_type: tv
    conditions:
      keywords: anime
    apply: Anime
``` 

All of the instances are set according to my Overseerr settings:

![image](https://github.com/user-attachments/assets/70548f88-e78d-41cd-8c3a-fa7b31ccb0f5)

But when I request Super Dragon Ball Heroes for example, it sends it to my id 0 instance, and not the Anime one.
Did I miss anything? The log file is practically empty, apart from the following.

> 2024-11-18 14:15:33 [INFO]: Validated config
> 2024-11-18 14:15:33 [INFO]: Server is running on port 8481

Thanks in Advance!
