### ISSUE TITLE
Quality Profile ID 1 Not Found

### ISSUE THREAD

**Issue by jamesgrimes** [varthe/Redirecterr#5]
I have redirecterr all set up, with webhooks firing and the filters behaving in the way I want them to but I am running into an issue when it attempts to approve a request. The requests are failing to be sent to radarr/sonarr because the quality id "1" is not found. Based on the README I would expect all instances to have a quality id 1. Do I need to find the quality profile id in each of the 'arrs?

error message from overseerr logs:
```
{
 "errorMessage": "Request failed with status code 400",
 "options": {
  "minimumAvailability": "released",
  "monitored": true,
  "profileId": 1,
  "qualityProfileId": 1,
  "rootFolderPath": "/data2/media/movies",
  "searchNow": true,
  "tags": [
   39
  ],
  "title": "The Boat That Rocked",
  "tmdbId": 18947,
  "year": 2009
 },
 "response": [
  {
   "attemptedValue": 1,
   "errorCode": "QualityProfileExistsValidator",
   "errorMessage": "Quality Profile does not exist",
   "formattedMessageArguments": [],
   "formattedMessagePlaceholderValues": {
    "propertyName": "Quality Profile Id",
    "propertyValue": 1
   },
   "propertyName": "QualityProfileId",
   "severity": "error"
  }
 ]
}
```

config.yml:
```
overseerr_url: "#######"
overseerr_api_token: "######"

instances:
  radarr: # Custom instance name
    server_id: 0
    root_folder: "/data2/media/movies"
    quality_profile_id: 1
    approve: true
  radarr_anime: # Custom instance name
    server_id: 0
    root_folder: "/data2/media/movies (anime)"
    quality_profile_id: 2 # Anime
    approve: true
  sonarr: # Custom instance name
    server_id: 0
    root_folder: "/data2/media/tv"
    quality_profile_id: 1
    approve: true
  sonarr_anime: # Custom instance name
    server_id: 0
    root_folder: "/data2/media/tv (anime)"
    quality_profile_id: 2 # Anime
    approve: true

filters:
  - media_type: movie
    conditions:
      keywords: anime # Match if keyword "anime" is present
    apply: radarr_anime # Apply Anime quality profile
  - media_type: movie
    conditions:
      keywords: # Exclude requests with keywords "anime" or "animation"
        exclude:
          - anime
    apply:
      - radarr
  - media_type: tv
    conditions:
      keywords: anime # Match if keyword "anime" is present
    apply: sonarr_anime # Apply Anime quality profile
  - media_type: tv
    conditions:
      keywords: # Exclude requests with keywords "anime" or "animation"
        exclude:
          - anime
    apply:
      - sonarr
```
